elsevier-core-engineering/replicator

api/consul.go
Supports Consul ACL token.
Dynamically identify all Nomad jobs with scaling policies defined.
Supports an enable/disable flag in scaling policy to allow testing.
=> Determine Jobs With Scaling Policy Documents in Consul KV.

api/aws.go, replicator/structs.go
Added ability to interface with the AWS autoscaling API to initiate scale-out and scale-in activities in a safe manner and can support the use of a cooldown to prevent thrashing.
=> api/aws: Add AWS Autoscaling API Capability

api/api.go, api/nomad.go, helper/funcs.go, replicator/runner.go
This change introduces additional support structures required to make scaling decisions for a Nomad cluster. 
New functionality provides the ability to:
- Calculate the percentage of overall cluster capacity consumed
- Calculate and track per-node consumption of overall cluster capacity 
- Determine the most-utilized resource across the cluster 
- Determine the least-allocated worker node 
- Initiate allocation draining for a worker node
In addition to new functionality, this change reduces the three allocation structs (`totalAllocationCapacity`, `taskAllocation` and `usedAllocationCapacity`) to a single object `AllocationResources` as these structs were tracking the same type of data with the same field names. 
Finally, in order to implement tracking of per-node consumption of overall …
=> api/nomad: Add Nomad Scaling Support

replicator/config.go, replicator/config_test.go
The addition of the ClusterScaling.CoolDown configuration param was not match with the appropriate default config value as well as the correct override mechanism for user defined values. This has now been fixed and the tests updated to pass and match the correct behavior.
=> Add default value for ClusterScaling.CoolDown with conf overrides.

dist/README.md, dist/systemd/replicator.service, dist/upstart/replicator.conf
The examples include upstart and systemd and allow users to quickly setup replicator as a system service.
=> Addition of sample daemon configs for various linux platforms.

replicator/cli.go
This PR adds the telemetry setup into the main entry point of replicator and has been tested on a test cluster and statsd endpoint to work correctly and be callable throughout the packages in replicator:
```
$ find ./ -name *.wsp
./runtime/num_goroutines/i-07d997ba0bd21a636.wsp
./runtime/alloc_bytes/i-07d997ba0bd21a636.wsp
./runtime/sys_bytes/i-07d997ba0bd21a636.wsp
./runtime/free_count/i-07d997ba0bd21a636.wsp
./runtime/malloc_count/i-07d997ba0bd21a636.wsp
./runtime/total_gc_runs/i-07d997ba0bd21a636.wsp
./runtime/heap_objects/i-07d997ba0bd21a636.wsp
./runtime/total_gc_pause_ns/i-07d997ba0bd21a636.wsp
./replicator/meaning_of_life/i-07d997ba0bd21a636.wsp
```
The custom gauge set was "meaning_of_life" which can be seen along with the default application metrics.
=> Add telemetry setup.

replicator/runner.go
This change ensures we perform scaling operations only when running on the known leader.
=> core: add leader safety check to runner 

api/aws.go, api/nomad.go, replicator/cli.go, replicator/runner.go
Initially all messages were being logged at Info and above which
causes a lot of noise. All standard messages have now been moved
to debug level so that only messages which change state will be
logged at Info or above.
=> Update logging levels on logging messages.

api/nomad.go
This function was left in place whilst another algorithm was tested;
this testing has now been completed successfully and this redundant
code should now be removed.
Close #24
=> Remove unused PercentageCapacityRequired function.

replicator/cli.go, version/version.go
This now allows replicator to log the version of replicator
including the pre-release currently available making the code
online clearer.
=> Smarter version details including pre-release details.

config/config.go, main.go, replicator/cli.go
The -config flag can now be used to configure replicator to use a
single file or a directory which contains a number configuration
files. When a directory is provided, all files are parsed and the
configs merged in lexicographic order.
=> Configuration can now come from a file or directory of files.

dist/README.md, dist/systemd/replicator.service, dist/upstart/replicator.conf
The README has been updated as well as the example upstart and
systemd files to reflect the ability for replicator to read its
configuration using a directory of files.
=> Update dist directory to match new replicator config ability.

api/consul.go, replicator/runner.go, replicator/structs/consul.go
Closes #25 
Unable to reproduce a deadlock when Consul is unavailable but Nomad is running, however, I've added a more detailed error message and ensured the runner will return immediately from `jobScaling` if we are unable to retrieve a list of job scaling policy documents.
This change also renames the `ListConsulKV` method to `GetJobScalingPolicies` to more accurately reflect its purpose as this method contains processing specific to job scaling policy documents. 
**Debug Output**
```
✘  ~/code/go/src/github.com/elsevier-core-engineering/replicator   consul-connection-bug  curl http://localhost:4646/v1/status
404 page not found
~/code/go/src/github.com/elsevier-core-engineering/replicator   consul-connection-bug  curl http://localhost:4646/v1/status/leader
"127.0.0.1:4647"% …
```
=> replicator/runner: ensure we do not hang when consul is unavailable

api/nomad.go
This change will detect when a cluster utilization is 0 for supported metrics (e.g. CPU, Memory). The evaluation method will attempt to initiate scale-in operation whenever the cluster is determined to be dormant thus ensuring we take the cluster down to the declared minimum size. 
The evaluation method short-circuits the scale-out section if the cluster is determined to be dormant.
Closes #38
=> api/nomad: Detect Dormant Cluster During Scaling Evaluation

README.md, command/agent/config.go, replicator/runner.go, replicator/structs/config.go
This makes the scaling_interval configurable and therefore allows
users to configure the interval at which replicator agent runs.
The parameter is configured in seconds and the default setting
is set to 10.
Closes #44
=> Add the scaling_interval config parameter to replicator agent.

client/aws.go, client/consul.go, client/consul_test.go, client/nomad.go, command/agent/config.go, command/agent/config_test.go, replicator/runner.go
This moves all external API calls and logic from the api package
to the client package. This name makes more sense and is more
consistant with other go packages and allows us to in the future
create an API for replicator.
Closes #42
=> Rename api package to client.

client/consul.go, replicator/runner.go
This change will modify the `client` package and `replicator/runner` to retrieve and evaluate all job scaling documents, even if scaling is set to `disabled` in the policy. 
This will allow users to evaluate the scaling actions Replicator would take without actually impacting the job. 
**Example Dry-Run Output**
```
May  3 21:31:52 ip-10-169-23-100 replicator[10905]: [DEBUG] core/runner: scaling for job "ceapp" has been disabled; a scaling operation (In) would have been requested for group "ceapp"
```
**Actual Scaling Operation**
```
May  3 21:32:02 ip-10-169-23-100 replicator[10905]: [INFO] api/nomad: scaling for job "ceapp" has been enabled; a scaling operation (In) will be requested for group "ceapp"
May  3 21:32:02 ip-10-169-23-100 replicator[10905]: [INFO] api/nomad: scaling action …
```
=> Allow Dry Run Operations Against Job Scaling Documents

client/aws.go, client/consul.go, client/nomad.go
This change implements protection against the divide by zero panic in #5. This panic can occur when the Nomad worker pool is in an unstable state resulting in Replicator detecting no healthy worker nodes. 
Once we evaluate the worker nodes and populate `NodeCount`, we will short-circuit the cluster scaling evaluation if `NodeCount` is 0. 
This change also modifies the logging prefixes to `client/nomad` and `client/aws` to reflect the renamed package.
Closes #5
=> Prevent Divide By Zero Panic When Replicator Detects No Healthy Worker Nodes

command/agent/config.go, command/agent/config_test.go
This change increases the default cluster scaling cooldown period from `300` seconds to `600` seconds to accommodate new node bootstrapping.
Closes #54.
=> Increase Default Cluster Scaling Cooldown Period

README.md, command/agent/agent.go, command/agent/config.go, command/agent/config_parse.go, command/init.go, replicator/structs/config.go
The replicator agent now supports passing all configuration params
as CLI flags. The CLI flags can be used in conjunction with config
files, CLI flags taking precedent.
Coses #60
=> Addition of CLI flags for all configuration parameters.

README.md, command/agent/agent.go, command/agent/config.go
The dev flag starts the Replicator agent in development mode. This
runs the Replicator agent with a configuration which is ideal for
development or local testing.
The configuration will still accept overrides from params passed
via CLI flags.
Closes #45
=> Add support for `dev` CLI flag.

command/agent/config_parse.go
When a rework of the configuration parsing was done to accomodate
CLI falgs both the cluster_scaling and job_scaling enabled flags
we wrongly prefixed with their top level key. This meant that the
config files params allowed did not match the config struct
mapstructure designation and so was failing to work as expected.
This updates the config_parse to check for the correct keys thus
allowing enabled to be set on cluster and job scaling.
Closes #75
=> Fix incorrect cluster_scaling and job_scaling enabled config keys.

client/aws.go, replicator/runner.go
Previously the function would assume that a call to terminate the
instance which completed successfully was enough to ensure the
eventual instance termination. This change now implements a ticker
so that the function confirms that the instance ends in the state
of 'terminated' before returning successfully.
Closes #71
=> AWS 'TerminateInstance' function now verifies instance terminated state.

replicator/runner.go
This change ensures the `runner` will evaluate the global job scaling enabled config flag when making job scaling decisions.
Previously, this config flag was ignored and only per-job scaling config was evaluated.
Closes #72
=> Evaluate Global Job Scaling Configuration Flag

client/aws.go, client/consul.go, client/nomad.go, command/agent/agent.go, replicator/runner.go
This commit introduces initial metrics which will help debug and
understand Replicator performance. The telemetry configuration
setup has also been updated to allow future additional endpoints
as well as sending the USR1 signal to output metrics to the stderr
log.
Closes #67
=> Make use of telemetry configuration by sending key metrics.

command/agent/agent.go, command/agent/config.go, command/agent/config_parse.go, replicator/runner.go, replicator/structs/config.go
A new configuration parameter has been added to allow users to
configure the scaling retry threshold, thus determining the number
of attempts and failures replicator will attempt to scale the
cluster out before disabling scaling. The default has been set to
2.
Closes #77
=> Make cluster scaling retry threshold a user configurable option.

client/consul.go, command/agent/agent.go, command/agent/config.go, command/agent/config_parse.go, command/agent/config_parse_test.go, replicator/structs/config.go
This change moves the `consul_key_location` and `consul_token` configuration parameters from the `job_scaling` section to top-level configuration parameters. 
Closes #92 and clears the way for #86, #83 and #32.
=> Move Consul Configuration Parameters To Top-Level

client/consul.go, replicator/runner.go, replicator/structs/consul.go, replicator/structs/nomad.go
This commit provides enhancements to the state
tracking mechanism including support for
persistent storage in a Consul Key/Value store.
When Replicator begins evaluating if a scaling
operation is required, it will first look for
persistent state tracking information and load
it into memory. If no persistent state tracking
information is found, or the attempt to retrieve
it fails, the in-memory data will be used.
This is critical to allowing Replicator to run as
a Nomad job or docker container while also
ensuring we can pick up where we left off. This
also clears the way for persistently locking the
daemon in `failsafe` mode after certain failure
modes are encountered (see #86 for more details).
Closes #83.
=> Support Persistent State Tracking

client/consul.go, client/nomad.go, command/agent/agent.go, replicator/leader.go, replicator/runner.go, replicator/structs/consul.go, replicator/structs/nomad.go
This requirement helps move Replicator towards being able to run
as a Nomad job. Each replicator instance will obtain a Consul
session and then attempt to gain a lock on a Consul KV. The session
is continually renewed in the background and non-leadership locking
instances will continue to attempt to gain the lock.
If a leader instance is shutdown, it will attempt to release its
session and lock allowing other instances to obtain the lock quicker
than waiting for the TTL to expire.
Telemetry has been added as a counter for leadership aquisition
events.
Closes #32
=> Replicator now runs leadership locking using Consul sessions +  KV

client/consul.go, command/agent/agent.go, command/agent/config.go
The Nomad and Consul clients are now stuffed into the config
struct after config parsing has occured meaning replicator
correctly uses the user specified endpoints. The Consul token is
also evaluated at this stage allowing us to remove all of the
Read/WriteOptions{} setups in client/consul.go.
Along with this the telemetry and logging gets setup in a new
function which allows replicator to correctly reload config
changes and apply them.
Closes #100
=> Correctly initialise clients after config parsing.

client/consul.go, command/agent/agent.go, command/base/config.go, command/base/config_parse.go, command/base/config_parse_test.go, command/base/config_test.go, command/failsafe.go, commands.go, replicator/failsafe.go, replicator/runner.go, replicator/structs/consul.go, replicator/structs/failsafe.go, replicator/structs/nomad.go
This commit introduces a distributed failsafe lock
that will prevent all running copies of Replicator
from taking any scaling actions if the daemon
detects enough consecutive critical failures to 
exceed the configured threshold.
Once a Replicator daemon has autonomously entered
failsafe mode, the lock flag is stored permanently
in the state tracking data. This allows the lock
to persist past daemon restarts, changes in leader
election or new copies of Replicator starting. To
resume normal behavior, an operator must explicitly
remove the failsafe lock.
This commit introduces a new CLI command,
`replicator failsafe`, that allows an operator to
administratively control the distributed failsafe
lock.
To implement this change, some restructuring of
the command package was required to allow …
=> Introduce Distributed Failsafe Mode

client/consul.go
This was previously hardcoded pending an update to the way in
which ConsulKeyLocation worked and was defaulted to. The change
has been completed and therefore the stateKey assignment can now
be performed dynamically using that config setting with state
prepended.
Closes #106
=> Update LoadState and WriteState methods to use dynamic key path.

client/aws.go, replicator/runner.go
This change brings in an evaluation between the desired ASG count
and the Nomad worker pool before scaling the cluster out. This
stops us incrementing the ASG count further if we have no need to
as Replicator tracks node launches and failures to join the
cluster.
ScaleOut will now also perform a check against the ASG MaxSize
before incrementing the count; as if the incrementation were to
violate the MaxSize the AWS call would fail anyway.
Closes #70
=> Evaluate cluster-node count against ASG desired before scaling.

README.md
This commit adds documentation for the `failsafe` command in the README and also provides more detailed documentation in the form of the following Wiki page:
```
Replicator is designed to automatically detect critical failures during scaling operations. If enough consecutive failures are detected, the failsafe circuit breaker trips and Replicator enters failsafe mode.
When operating in failsafe mode, all running copies of Replicator will be prevented from taking any scaling actions. This behavior is designed to prevent Replicator from further complicating a potentially malfunctioning cluster.
Once Replicator has detected enough consecutive critical faults and the failsafe circuit breaker has been tripped, the failsafe lock flag is persistently updated in the state tracking data shared by …
```
=> Add Failsafe Mode Documentation

command/failsafe.go, replicator/failsafe.go, replicator/structs/failsafe.go
This commit fixes #112 by ensuring the failsafe
mode circuit breaker will always fail properly
once tripped automatically or via administrative
interface.
Closes #112
=> Always Fail Failsafe Circuit Breaker After Trip

command/agent/agent.go, command/base/config.go, command/base/config_parse.go, replicator/cluster_scaling.go, replicator/cluster_scaling_test.go, replicator/runner.go, replicator/structs/config.go, replicator/structs/nomad.go
Previously Replicator would perform cluster scaling operations if
only the cool-down had been met; which met Replicator would scale
on fleeting load in the cluster.
To combat this, a new parameter, cluster-scaling-threshold has been
added. Replicator must now want to perform a cluster scaling action
for n consecutive times which is set by the new param before a
scaling operation will be actioned.
The default config value is set to 3 and 1 in the default and dev
configs respectively. Tests have also been added for the new func
within the replicator package.
Closes #73
=> ClusterScalingTheshold parameter is now used to determine scaling.

command/agent/agent.go, notifier/pagerduty.go, replicator/structs/config.go
Replicator now initializes configured notification backends and
stores these as a slice within the config struct. This then allows
notifications to be sent to each configured backend via a simple
for loop.
Closes #107
=> Initialize notification backends and store in config struct.

command/agent/agent.go
This commit fixes #122 that results in Replicator
failing to initialize when the `-cluster-min-size`
CLI flag is passed to the `replicator agent`
command.
Closes #122.
=> Correct Cluster Min Size CLI Flag Name

replicator/runner.go
This commit ensures Replicator will persistently
write state tracking information to the Consul
Key/Value Store if no pre-existing state tracking
information exists.
Before this change, no distributed state tracking
information would be available until a scaling
action was initiated.
Closes #120.
=> Persist Initial State Tracking Information

client/nomad.go, replicator/runner.go, replicator/structs/nomad.go
This commit adds intelligence to Replicator to
determine if it is running as a Nomad job and if
so, to attempt to identify the agent node on which
it is running.
If the node is identified, it is registered in the
state tracking information as a protected node.
The least-allocated node discovery method has
been modified to exclude the protected node during
the discovery process.
This feature is only used by the elected Replicator
leader. If this feature encounters errors, the
original behavior is retained.
Closes #119.
=> Protect Nomad Agent Node Running Replicator Leader

replicator/leader.go
Previously Replicator logged that it was attempting to obtain a
lock but never reported if it couldn't obtain the lock. This
change adds a debug log message when this occurs.
Closes #121
=> Add DEBUG logging when leadership lock is not obtained.

command/agent/agent.go, notifier/notifier.go, notifier/pagerduty.go, replicator/failsafe.go, replicator/runner.go, replicator/structs/nomad.go
Using the notification backends Replicator will now send a
notification to each backend when failsafe mode is entered.
Closes #116
=> Replicator will send a notification if failsafe mode is enabled

Dockerfile, example-jobs/replicator-docker.nomad, example-jobs/replicator-exec.nomad
This commit introduces a source Docker image and
example Nomad job files to run Replicator in using
either the `exec` or `docker` driver.
Closes #102.
=> Add Docker Image and Example Job Files

replicator/cluster_scaling.go, replicator/cluster_scaling_test.go, replicator/runner.go
The introduction of ScalingThreshold meant we had additional
state fields. When these in-memory ints were getting updated, the
change was not being persisted to Consul. Therefore upon state
read the in-memory values were overwritten with the starting
values.
The checkScalingThreshold function will now finish by writing
update state to the persistent store, meaning evaluations are not
over-written or thrown away.
Closes #134
=> Replicator checkScalingThreshold now writes persistent state.

command/failsafe.go, replicator/failsafe.go, replicator/failsafe_test.go
This commit ensures the failure count of a scalable resource is
reset when an operator resets the failsafe circuit breaker.
This resolves a bug that results in the failsafe circuit breaker
always being tripped for a scalable resource at the next scaling
evaluation, if the circuit breaker was tripped automatically -
that is, not by an operator.
A test has been added to prove the fix. Also includes small
fixes in the `failsafe` command help verbage.
Closes #188.
=> Reset Failure Count When Exiting Failsafe

client/aws.go, replicator/cluster_scaling.go
This change removes some fairly useless aws metrics and adds finer
detail, including the worker pool name and success/failure result
when cluster scaling activites are actioned.
=> Improve accuracy and detail of cluster_scaling telemetry metrics.

client/aws.go, client/cluster_scaling.go, client/nomad.go, client/nomad_test.go, replicator/cluster_scaling.go, replicator/structs/nomad.go
This commit enhances and improves the logging produced by cluster
scaling when Replicator is running at an `INFO` log level.
=> Improve Cluster Scaling Logging In INFO Log Level

client/nomad.go, replicator/cluster_scaling.go, replicator/node_protection.go, replicator/runner.go, replicator/structs/nomad.go, replicator/structs/state.go, version/version.go
If Replicator wins the leader election, it automatically determines
if it is running as a Nomad job and attempts to protect the worker
pool node hosting its allocation.
If a node is marked as protected, Replicator will consider it
ineligible when identifying a node for scale in.
This commit improves the node protection mechanism, provides some
organization and ensures the `LeastAllocatedNode` method in the
`client/nomad` package actually uses this value during evaluation.
Closes #197.
=> Improve Node Protection Mechanism

client/nomad.go, replicator/structs/nomad.go
We recently evaluated replicator for our stack and found a couple of bugs making it unusable for us.
This is the way we fixed them.
- When a scaling action is set, it stays until another scaling action is set, it is never reset when the values are within a healthy threshold. Solved by setting `gsp.ScaleDirection` to `ScalingDirectionNone` before evaluating.
- When calculating reserved resources the `groupPolicy.Tasks.Resources.CPUMHz` and `groupPolicy.Tasks.Resources.MemoryMB` accumulate without being reset between cycles, making the metric approach 0% over time. Fixed this by setting them to 0 before every evaluation.
- Metric data for all jobs in a group are collected, but they overwrite each other, so only the last processed is used for the evaluation. Fixed this by making the …
=> Nomad job_scaling logic fixes

README.md, command/init.go
- IAM policy doesn't allow whitespaces in Sid
- Init was generating cluster old scaling meta tags
=> Docs fixes

CHANGELOG.md, README.md, client/cluster_scaling.go, client/node_discovery.go, client/node_discovery_test.go, cloud/aws/aws_cloud_provider.go, command/init.go, replicator/structs/node_discovery.go
This commit removes the explicit min/max threshold values for worker
pools. The cloud provider is now solely responsible for dynamically
determining the min/max thresholds from the underlying scaling group.
If the cloud provider safety check determines a scaling operation
would violate either the min or max thresholds, the scaling event
will be denied.
Closes #205
=> Remove Explicit Cluster Scaling Thresholds

client/job_scaling_policies.go
Fix state if Job ID and Job Name are not the same, and to function that had to receive Job ID Job Name was passed
=> job-name-id-missmatch-fix

client/job_scaling_policies.go, client/nomad.go
This commit removes all internal constants used to represent the status
of Nomad resources (e.g. jobs, allocations, etc.) in favor of exported
constants from the Nomad `structs` package.
=> Remove Internal Nomad Status Constants

.travis.yml
This commit instructs Travis CI to use the latest available patch within the `Go 1.9.x` release.
=> Update Travis Script

client/job_scaling.go, client/job_scaling_policies.go, client/nomad.go
In order to lower the pressure Replicator puts on the Nomad leader
this change introduces adding the QueryOption `AllowStale: true`
to all calls which are safe to do so. The staleness as stated in
the Nomad docs will be less than 50ms, therefore this should not
have any negative impact in the running of Replicator.
Closes #224
=> Use `AllowStale: true` in all JobScaling actives where its safe.

command/agent/agent.go, command/base/config.go, command/base/config_parse.go, command/base/config_parse_test.go, replicator/cluster_scaling.go, replicator/job_scaling.go, replicator/runner.go, replicator/structs/config.go
This commit changes the concurrency model for both job and worker
pool scaling operations. Previously, Replicator would initiate a
concurrent thread for each scalable resource with no upper-bound
limit to the number of concurrent scaling operations.
Under this patch, Replicator introduces a new configuration flag,
`-scaling-concurrency` which defaults to `10`. Under the new
concurrency model, Replicator will create up to the maximum
declared number of scaling workers. Scalable resources are passed
to the worker threads via a buffered channel and the async methods
perform work accounting via a `sync.WaitGroup`.
If the number of scalable resources is less than the declared max
concurrency, only the required number worker threads are instantiated.
Closes #223 and #221
=> Implement Concurrency Limits On Scaling Operations

command/agent/agent.go
This adds a logging line in the agent command to log if Replicator
tries to start and the RPC bind address is in use. Previously
this would just silently fail.
Closes #241
=> Fix issue where Replicator wouldn't log when RPC bind is in use.

api/status.go, client/consul.go, command/agent/http.go, command/agent/status_endpoint.go, replicator/server.go, replicator/status_endpoint.go, replicator/structs/consul.go, replicator/structs/structs.go
This commit introduces the first Replicator API endpoint which can
be called at `/v1/status/leader` and returns a JSON block that
details the leader Replicator instance which currently holds the
Consul lock.
Example response:
```
{
"NodeID":"REDACTED",
"SessionID":"5f9b250f-70bd-a59a-fd44-9c4e54f5ac27"
}
```
Once this has been accepted I will raise a ticket to document the API and this endpoint.
Closes #239
=> Add /status/leader API endpoint functionality.

client/nomad.go
This commit fixes a bug in the `LeastAllocatedNode` method that
results in an error when Replicator attempts to initiate a cluster
scale-in operation if the prioritized scaling metric is set to
`ScalingMetricDisk`.
Closes #240
=> Fix Cluster Scaling When Disk Metric Prioritized

client/consul.go, client/node_discovery.go, client/node_discovery_test.go, cloud/aws/aws_cloud_provider.go, cloud/cloud_provider.go, cloud/cloud_provider_test.go, helper/funcs.go, helper/funcs_test.go, replicator/server.go, replicator/structs/consul.go, replicator/structs/node_discovery.go, replicator/structs/nomad.go
This commit introduces support for minimizing the required Replicator
configuration that must be added to the client meta section.
A fallback configuration lookup feature has been added for the node
discovery mechanism. With this feature, when node discovery
encounters a node where only the `replicator_worker_pool` meta
parameter is set, Replicator will attempt to find the rest of the
worker pool configuration parameters in the Consul key/value store.
Replicator searches down the Consul root key path defined in
`consul_key_root`.
To use this feature, you would set the worker pool name in each
node configuration:
```
meta {
"replicator_worker_pool" = "example-worker-pool"
}
```
Then place the full worker pool configuration in a Consul key
located at …
=> Implement Worker Pool Configuration Fallback From Consul

.travis.yml
The list of available travis environment variables is [here](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables).
Closes elsevier-core-engineering/replicator#235
=> fix: do not run make release unless the travis build is for a git tag

Dockerfile.build
Adds a `Dockerfile.build` to help with doing local builds for testing... if this is interesting I'd be happy to add a line or two to the docs.
=> Add dockerfile for building replicator image

logging/logging.go
Logging messages will now be logged in the formt
`2018/01/11 10:58:09 GMT [INFO]` which aids debugging in setups
where Replicator runs as a Nomad job.
Closes #253
=> Update logging messages to include date, time and zone.

cloud/aws/aws_asg_util.go
In the event that the ASG is associated with an ELB the default period
for connection draining is 300 seconds / 5 minutes. This pushes the
timeout further out to 10 minutes.
Perhaps the ASG should be queried for the connection draining period and
have that added to the timeout instead?
=> Increase timeout for ASG scaling result

README.md, client/job_scaling.go, client/nomad.go, cloud/aws/aws_asg_util.go, cloud/aws/aws_ec2_util.go, helper/funcs.go
Ref: https://golang.org/pkg/time/#Tick
Apparently, `.Tick()` "leaks", `.NewTicker()` should be used instead. This could answer the weird state that I'm seeing replicator experience where it will immediately timeout when attempting to `getMostRecentInstance`, it attemps and timeouts all in the same timestamp:
=> Fix timeout to use Ticker vs Tick

replicator/cluster_scaling.go, replicator/job_scaling.go
Adding an anonymous func + adding `wg.Done()` above in order to guarantee that it gets called. This will prevent any edge case or future added extension that a developer may miss and prevent the `WaitGroup` from completing.
Probably easier to view these changes with the `?w=1` query parameter added to the URI.
=> Defer wg.Done

client/job_scaling.go
This fixes the first issue found when upgrading to 0.8.0, maybe more coming. This change is backwards compatible with Nomad versions < 0.8.0.
```
Apr 13 22:21:19 ip-10-2-19-141 replicator[2881]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 13 22:21:19 ip-10-2-19-141 replicator[2881]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb13a0e]
Apr 13 22:21:19 ip-10-2-19-141 replicator[2881]: 
Apr 13 22:21:19 ip-10-2-19-141 replicator[2881]: goroutine 27 [running]:
Apr 13 22:21:19 ip-10-2-19-141 replicator[2881]: github.com/elsevier-core-engineering/replicator/client.(*nomadClient).IsJobInDeployment(0xc420166138, 0xc420023200, 0x1c, 0xa)
Apr 13 22:21:19 ip-10-2-19-141 replicator[2881]: #011/go/src/github.com/elsevier-core-engineering/replicator/clie …
```
=> Check if deployment exists, if not return false
